server:
  port: 0
  servlet:
    context-path: /market
spring:
  application:
    name: ms-auth

jwt:
  secret: kjfgeih23827asuhwxn281kan

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
