server:
  port: 5555

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/*/auth/**
        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/api/*/products/**
        - id: ms-payments
          uri: lb://ms-payments
          predicates:
            - Path=/api/*/payments/**
        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/api/*/order/**,/api/*/cart/**
    loadbalancer:
      ribbon:
        enabled: false

jwt:
  secret: kjfgeih23827asuhwxn281kan

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
