server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nessing/MarketSpring
          default-label: master
          username:
          password:
          clone-on-start: true
          search-paths: configs

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
