server:
  port: 0

spring:
  application:
    name: ms-products
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:marketdb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /db-console

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}

jwt:
  secret: kjfgeih23827asuhwxn281kan
